TTCM_RestaurentManager/Models/ThongKe.cs
namespace TTCM_RestaurentManager.Models
{
    public class ThongKe
    {
        public int dishId;

        public ThongKe(int dishId)
        {
            this.dishId = dishId;
        }

        public String dishName;
        public String dishImg;

        public int soLuong;

        public ThongKe(int dishId, String dishName, string dishImg)
        {
            this.dishId = dishId;
            this.dishName = dishName;
            this.dishImg = dishImg;
        }
    }
}

TTCM_RestaurentManager/Areas/Admin/Controllers/HomeAdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Differencing;
using Microsoft.EntityFrameworkCore;
using TTCM_RestaurentManager.Models;
using System.Web;
using System.IO;
using X.PagedList;

namespace TTCM_RestaurentManager.Areas.Admin.Controllers
{
    [Area("admin")]
    [Route("homeadmin")]
    public class HomeAdminController : Controller
    {
        RestaurentManagerContext ResDb = new RestaurentManagerContext();
        //private readonly IWebHostEnvironment _env;

        //public HomeAdminController(IWebHostEnvironment env)
        //{
        //    _env = env;
        //}

        [Route("")]
		[Route("index")]
		public IActionResult Index()
		{
			return View();
		}

		[Route("thongke")]
		[HttpPost]
		public IActionResult ThongKe(DateTime ngayTao)
		{
			// Lấy danh sách các hóa đơn được tạo từ ngày ngayTao trở đi
			List<HoaDon> hds = ResDb.HoaDons.Where(x => x.NgayTao >= ngayTao).ToList();

			// Lấy danh sách mã các món ăn từ các hóa đơn này
			List<int> dishIds = hds.Select(x => (int)x.MaMa).Distinct().ToList();

			// Lấy danh sách chi tiết các món ăn và tên các món ăn
			List<ThongKe> tks = new List<ThongKe>();
			var thongKes = (from hd in ResDb.HoaDons
							join ts in ResDb.MonAns on hd.MaMa equals ts.MaMa
							where dishIds.Contains((int)hd.MaMa)
							select new { hd.MaMa, hd.SoLuong, ts.TenMa, ts.AnhMa }).ToList();

			// Khởi tạo danh sách ThongKe, mỗi phần tử tương ứng với một món ăn
			foreach (int dishId in dishIds)
			{
				tks.Add(new ThongKe(dishId));
			}

			// Tính tổng số lượng của mỗi món ăn
			foreach (ThongKe tk in tks)
			{
				int dishId = tk.dishId;
				int count = 0;
				foreach (var thongKe in thongKes)
				{
					if (thongKe.MaMa == dishId)
					{
						count += (int)thongKe.SoLuong;
						tk.dishName = thongKe.TenMa;
                        tk.dishImg = thongKe.AnhMa;
					}
				}
				tk.soLuong = count;
			}

			// Sắp xếp danh sách theo số lượng giảm dần và trả về view
			List<ThongKe> tt = tks.OrderByDescending(x => x.soLuong).ToList();
			return View(tt);
		}


		[Route("listDish")]
        public IActionResult LishDish(string price)
        {
            var lstDish = ResDb.MonAns.ToList();
            if (price == "all")
            {
                lstDish = ResDb.MonAns.AsNoTracking().ToList();
            }
            if (price == "above")
            {
                lstDish = ResDb.MonAns.AsNoTracking().Where(x => x.Gia > 15).ToList();
            }
            else if (price == "below")
            {
                lstDish = ResDb.MonAns.AsNoTracking().Where(x => x.Gia <= 15).ToList();
            }
            return View(lstDish);
        }
        [Route("listbookdish")]
        public IActionResult KHTheoTour(int khdish)
        {
            var kh = (from c in ResDb.KhachHangs
                      join t in ResDb.HoaDons on c.MaKh equals t.MaKh
                      join q in ResDb.MonAns on t.MaMa equals q.MaMa
                      where q.MaMa == khdish
                      select c);
            return View(kh);
        }



        [Route("addDish")]
        [HttpGet]
        public IActionResult AddDish()
        {
            ViewBag.MaLoaiMa = new SelectList(ResDb.LoaiMonAns.ToList(), "MaLoaiMa", "TenLoaiMa");
            return View();
        }
        [ValidateAntiForgeryToken]
        [Route("addDish")]
        [HttpPost]
        public IActionResult AddDish(MonAn dish)
        {
           
                dish.AnhMa = dish.formFile.FileName.Split(".")[0];
                ResDb.MonAns.Add(dish);
                ResDb.SaveChanges();
                return RedirectToAction("listDish");
            
            //if (uploadanh != null && uploadanh.Length > 0)
            //{
            //    int id = ResDb.MonAns.ToList().Last().MaMa;
            //    string fileName = "f" + id.ToString();
            //    //string extension = Path.GetExtension(uploadanh.FileName);
            //    string _FileName = fileName;// + extension;
            //    string _path = Path.Combine(_env.ContentRootPath, "Assets/images", _FileName);

            //    using (var stream = new FileStream(_path, FileMode.Create))
            //    {
            //        uploadanh.CopyTo(stream);
            //    }

            //    MonAn unv = ResDb.MonAns.FirstOrDefault(x => x.MaMa == id);
            //    unv.AnhMa = fileName;
            //    ResDb.SaveChanges();
            //}

            return View(dish);
        }


        [Route("editDish")]
        public IActionResult EditDish(int edish)
        {
            var dishedit = ResDb.MonAns.SingleOrDefault(x => x.MaMa == edish);
            ViewBag.MaLoaiMa = new SelectList(ResDb.LoaiMonAns.ToList(), "MaLoaiMa", "TenLoaiMa");
            return View(dishedit);
        }

        [Route("editDish")]
        [HttpPost]
        public IActionResult EditDish(MonAn eddish)
        {
            var dish = ResDb.MonAns.Find(eddish.MaMa);
          
                
                dish.MaMa = eddish.MaMa;
                dish.TenMa = eddish.TenMa;
                dish.ChiTietMa = eddish.ChiTietMa;
                dish.Gia = eddish.Gia;
                dish.AnhMa = eddish.formFile.FileName.Split(".")[0];
                dish.MaLoaiMa = eddish.MaLoaiMa;
                dish.SoLuongMa = eddish.SoLuongMa;
                dish.Active = eddish.Active;
                dish.IsDeleted = eddish.IsDeleted;
                ResDb.SaveChanges();
                return RedirectToAction("listDish");
        
            return View(eddish);
        }
        [Route("deleteDish")]
        public IActionResult DeleteDish(int madish, int malma)
        {
            // Lấy danh sách tour cần xóa dựa trên mã tour
            var listdish = ResDb.MonAns.Where(x => x.MaMa == madish);

            // Kiểm tra xem mã nhân viên có tồn tại trong danh sách tour hay không
            var loai = ResDb.LoaiMonAns.Where(x => x.MaLoaiMa == malma).FirstOrDefault();
            //var cttour = Tourdb.Cttours.Where(x => x.MaCttour == mact).FirstOrDefault();
            if (loai != null)
            {
                foreach (var item in listdish)
                {
                    if (item.MaLoaiMa == malma)
                    {
                        return RedirectToAction("listDish");
                    }
                }
            }

            // Update trường IsDeleted của các món ăn trong danh sách và lưu thay đổi
            if (listdish != null)
            {
                foreach (var item in listdish)
                {
                    item.IsDeleted = 1;
                }
                ResDb.SaveChanges();
            }

            // Update trường IsDeleted của món ăn dựa trên mã món ăn và mã loại món ăn và lưu thay đổi
            var dish = ResDb.MonAns.FirstOrDefault(x => x.MaMa == madish && x.MaLoaiMa == malma);
            if (dish != null)
            {
                dish.IsDeleted = 1;
                ResDb.SaveChanges();
            }

            // Chuyển hướng đến trang danh sách món ăn
            return RedirectToAction("listDish");
        }

        /////BookTable
        [Route("listTable")]
        public IActionResult LishTable(string table)
        {
            var lstTable = ResDb.DatBans.ToList();
           
            if (table == "all")
            {
                lstTable = ResDb.DatBans.AsNoTracking().ToList();
            }
            if (table == "2")
            {
                lstTable = ResDb.DatBans.AsNoTracking().Where(x => x.SoLuongNguoi == 2).ToList();
            }
            else if (table == "3")
            {
                lstTable = ResDb.DatBans.AsNoTracking().Where(x => x.SoLuongNguoi == 3).ToList();
            }
            else if (table == "4")
            {
                lstTable = ResDb.DatBans.AsNoTracking().Where(x => x.SoLuongNguoi == 4).ToList();
            }
            else if (table == "5")
            {
                lstTable = ResDb.DatBans.AsNoTracking().Where(x => x.SoLuongNguoi == 5).ToList();
            }
            else if (table == "6")
            {
                lstTable = ResDb.DatBans.AsNoTracking().Where(x => x.SoLuongNguoi == 6).ToList();
            }
            return View(lstTable);
        }


        [Route("editTable")]
        public IActionResult EditTable(int id)
		{
            var tableEdit = ResDb.DatBans.SingleOrDefault(x => x.Id == id);
			return View(tableEdit);
        }
		[Route("editTable")]
		[HttpPost]
		public IActionResult EditTable(DatBan datBan)
		{
			var table = ResDb.DatBans.Find(datBan.Id);
			if (ModelState.IsValid)
			{
				table.Id = datBan.Id;
				table.HoTen = datBan.HoTen;
				table.SoDienThoai = datBan.SoDienThoai;
				table.Email = datBan.Email;
				table.NgayDatBan = datBan.NgayDatBan;
				table.SoLuongNguoi = datBan.SoLuongNguoi;
				table.GhiChu = table.GhiChu;
				ResDb.SaveChanges();
				return RedirectToAction("listTable");
			}
			return View(table);
		}
        [Route("deleteTable")]
        public IActionResult DeleteTable(int maTable)
        {
            // Lấy danh sách tour cần xóa dựa trên mã tour
            var listtable = ResDb.DatBans.Where(x => x.Id == maTable);
            // Xóa tour dựa trên mã tour và lưu thay đổi
            var table = ResDb.DatBans.Find(maTable);
            if (table != null)
            {
                ResDb.Remove(table);
                ResDb.SaveChanges();
            }

            // Chuyển hướng đến trang lịch sử thêm tour
            return RedirectToAction("listTable");
        }


        /////ListStaff
        [Route("addStaff")]
        [HttpGet]
        public IActionResult AddStaff()
        {
            return View();
        }
        [ValidateAntiForgeryToken]
        [Route("addStaff")]
        [HttpPost]
        public IActionResult AddStaff(NhanVien nv)
        {
            if (ModelState.IsValid)
            {
                ResDb.NhanViens.Add(nv);

TTCM_RestaurentManager/Areas/Admin/Views/HomeAdmin/AddDish.cshtml
@model TTCM_RestaurentManager.Models.MonAn
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "AddDish";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Add Dish</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="AddDish" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TenMa" class="control-label"><a>Tên món ăn</a></label>
                <input asp-for="TenMa" class="form-control" />
                <span asp-validation-for="TenMa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChiTietMa" class="control-label"><a>Chi tiết món ăn</a></label>
                <input asp-for="ChiTietMa" class="form-control" />
                <span asp-validation-for="ChiTietMa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gia" class="control-label"><a>Giá</a></label>
                <input asp-for="Gia" class="form-control" />
                <span asp-validation-for="Gia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnhMa" class="control-label"><a>Ảnh món ăn</a></label>
                <input asp-for="AnhMa" class="form-control" />
                <input asp-for="formFile" class="form-control" />
                <span asp-validation-for="AnhMa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoLuongMa" class="control-label"><a>Số lượng món ăn</a></label>
                <input asp-for="SoLuongMa" class="form-control" />
                <span asp-validation-for="SoLuongMa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaLoaiMa" class="control-label"><a>Loại món ăn</a></label>
                <select asp-for="MaLoaiMa" class ="form-control" asp-items="ViewBag.MaLoaiMa"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="listDish">Back to List</a>
</div>

TTCM_RestaurentManager/Areas/Admin/Views/HomeAdmin/AddStaff.cshtml
@model TTCM_RestaurentManager.Models.NhanVien
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "AddStaff";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Add Staff</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="AddStaff">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TenNv" class="control-label"><p>Tên nhân viên</p></label>
                <input asp-for="TenNv" class="form-control" />
                <span asp-validation-for="TenNv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChucVu" class="control-label"><p>Chức vụ</p></label>
                <input asp-for="ChucVu" class="form-control" />
                <span asp-validation-for="ChucVu" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Sdtnv" class="control-label"><p>Số điện thoại</p></label>
                <input asp-for="Sdtnv" class="form-control" />
                <span asp-validation-for="Sdtnv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailNv" class="control-label"><p>Email</p></label>
                <input asp-for="EmailNv" class="form-control" />
                <span asp-validation-for="EmailNv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="listStaff">Back to List</a>
</div>

TTCM_RestaurentManager/Areas/Admin/Views/HomeAdmin/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using TTCM_RestaurentManager.Models;
@model List<ThongKe>

<div class="tab-content">
	<div class="tab-pane active">
		<div class="table-data">
			<div class="order">
				<div class="head">
					<h3>Số món ăn được bán </h3>
						<div class="status pending">
							<form class="form" method="POST" asp-controller="HomeAdmin" asp-action="thongke">
								<h6>Check-In</h6>
								<input class="input--style-1" type="text" name="ngayTao" placeholder="mm/dd/yyyy" id="input-start">					
								<button class="btn-sm btn-gradient-danger" type="submit">search</button>
							</form>
						</div>
				</div>
			</div>
		</div>
	</div>
</div>

TTCM_RestaurentManager/Areas/Admin/Views/HomeAdmin/LishDish.cshtml
@model IEnumerable<TTCM_RestaurentManager.Models.MonAn>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "LishDish";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
    .snip1582 {
        background-color: #c47135;
        border: none;
        color: #ffffff;
        cursor: pointer;
        display: inline-block;
        font-family: 'BenchNine', Arial, sans-serif;
        font-size: 1em;
        font-size: 13px;
        line-height: 1em;
        margin: 15px 40px;
        outline: none;
        padding: 12px 40px 10px;
        position: relative;
        text-transform: uppercase;
        font-weight: 700;
    }

        .snip1582:before,
        .snip1582:after {
            border-color: transparent;
            -webkit-transition: all 0.25s;
            transition: all 0.25s;
            border-style: solid;
            border-width: 0;
            content: "";
            height: 24px;
            position: absolute;
            width: 24px;
        }

        .snip1582:before {
            border-color: #c47135;
            border-top-width: 2px;
            left: 0px;
            top: -5px;
        }

        .snip1582:after {
            border-bottom-width: 2px;
            border-color: #c47135;
            bottom: -5px;
            right: 0px;
        }

        .snip1582:hover,
        .snip1582.hover {
            background-color: #c47135;
        }

            .snip1582:hover:before,
            .snip1582.hover:before,
            .snip1582:hover:after,
            .snip1582.hover:after {
                height: 100%;
                width: 100%;
            }
</style>

<script>
    $(document).ready(function () {


        // inspired by http://jsfiddle.net/arunpjohny/564Lxosz/1/
        $('.table-responsive-stack').find("th").each(function (i) {

            $('.table-responsive-stack td:nth-child(' + (i + 1) + ')').prepend('<span class="table-responsive-stack-thead">' + $(this).text() + ':</span> ');
            $('.table-responsive-stack-thead').hide();
        });





        $('.table-responsive-stack').each(function () {
            var thCount = $(this).find("th").length;
            var rowGrow = 100 / thCount + '%';
            //console.log(rowGrow);
            $(this).find("th, td").css('flex-basis', rowGrow);
        });




        function flexTable() {
            if ($(window).width() < 768) {

                $(".table-responsive-stack").each(function (i) {
                    $(this).find(".table-responsive-stack-thead").show();
                    $(this).find('thead').hide();
                });


                // window is less than 768px
            } else {


                $(".table-responsive-stack").each(function (i) {
                    $(this).find(".table-responsive-stack-thead").hide();
                    $(this).find('thead').show();
                });



            }
            // flextable
        }

        flexTable();

        window.onresize = function (event) {
            flexTable();
        };






        // document ready
    });


        // Search




</script>

<div class="tab-content">
    <div class="tab-pane active">
        <div class="table-data">
            <div class="order">
                <div class="head">
                    <h3>Danh Sách Món Ăn </h3>
                    <i class='bx bx-search'></i>
                    <i class='bx bx-filter'></i>
                    <div class="status pending">
                        <form action="/search" method="get">
                            <label for="price">Price:</label>
                            <select id="price" name="price">
                                <option value="all">All</option>
                                <option value="above">Above $15 </option>
                                <option value="below">Below $15 </option>
                            </select>
                            <button class="btn-sm btn-gradient-danger" type="submit" asp-action="listDish">Search</button>
                        </form>
                    </div>
                    <div>
                        <a asp-controller="HomeAdmin" asp-action="AddDish" class="create">
                            <button type="button" class="snip1582" asp-controller="HomeAdmin" asp-action="AddDish">
                                <i></i>Create New
                            </button>
                        </a>
                    </div>
                </div>
                <table>
                    <thead>
                        <tr>
                            
                            <th style="width:20%">
                                Tên Món Ăn
                            </th>
                            
                           
                            <th>
                                Giá
                            </th>
                            <th>
                                Số lượng
                            </th>
                            <th>
                                Active
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                
                                <td>
                                    @Html.DisplayFor(modelItem => item.TenMa)
                                </td>
                                
            
                                <td>
                                    @Html.DisplayFor(modelItem => item.Gia)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SoLuongMa)
                                </td>
                                <td>
                                    @if (item.Active == 0)
                                    {
                                        <span class="status pending">Pending</span>
                                    }
                                    else if (item.Active == 1)
                                    {
                                        <span class="status completed">Approved</span>
                                    }
                                </td>
                                <td>
                                    <a class="btn-sm btn-gradient-dark " asp-action="editDish" asp-route-edish="@item.MaMa">Edit</a>
                                    @*<a class="btn-sm btn-gradient-info" asp-controller="home" asp-action="TourDetail" asp-route-matour="@item.MaTour">Details</a>*@
                                    <a class="btn-sm btn-gradient-info" asp-action="listbookdish" asp-route-khdish="@item.MaMa">Details</a>
                                    <a class="btn-sm btn-gradient-danger" asp-action="deleteDish" asp-route-madish="@item.MaMa">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

TTCM_RestaurentManager/Areas/Admin/Views/HomeAdmin/ListStaff.cshtml
@model IEnumerable<TTCM_RestaurentManager.Models.NhanVien>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "ListStaff";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
    .snip1582 {
        background-color: #c47135;
        border: none;
        color: #ffffff;
        cursor: pointer;
        display: inline-block;
        font-family: 'BenchNine', Arial, sans-serif;
        font-size: 1em;
        font-size: 13px;
        line-height: 1em;
        margin: 15px 40px;
        outline: none;
        padding: 12px 40px 10px;
        position: relative;
        text-transform: uppercase;
        font-weight: 700;
    }

        .snip1582:before,
        .snip1582:after {
            border-color: transparent;
            -webkit-transition: all 0.25s;
            transition: all 0.25s;
            border-style: solid;
            border-width: 0;
            content: "";
            height: 24px;
            position: absolute;
            width: 24px;
        }

        .snip1582:before {
            border-color: #c47135;
            border-top-width: 2px;
            left: 0px;
            top: -5px;
        }

        .snip1582:after {
            border-bottom-width: 2px;
            border-color: #c47135;
            bottom: -5px;
            right: 0px;
        }

        .snip1582:hover,
        .snip1582.hover {
            background-color: #c47135;
        }

            .snip1582:hover:before,
            .snip1582.hover:before,
            .snip1582:hover:after,
            .snip1582.hover:after {
                height: 100%;
                width: 100%;
            }
</style>

<script>
    $(document).ready(function () {


        // inspired by http://jsfiddle.net/arunpjohny/564Lxosz/1/
        $('.table-responsive-stack').find("th").each(function (i) {

            $('.table-responsive-stack td:nth-child(' + (i + 1) + ')').prepend('<span class="table-responsive-stack-thead">' + $(this).text() + ':</span> ');
            $('.table-responsive-stack-thead').hide();
        });





        $('.table-responsive-stack').each(function () {
            var thCount = $(this).find("th").length;
            var rowGrow = 100 / thCount + '%';
            //console.log(rowGrow);
            $(this).find("th, td").css('flex-basis', rowGrow);
        });




        function flexTable() {
            if ($(window).width() < 768) {

                $(".table-responsive-stack").each(function (i) {
                    $(this).find(".table-responsive-stack-thead").show();
                    $(this).find('thead').hide();
                });


                // window is less than 768px
            } else {


                $(".table-responsive-stack").each(function (i) {
                    $(this).find(".table-responsive-stack-thead").hide();
                    $(this).find('thead').show();
                });



            }
            // flextable
        }

        flexTable();

        window.onresize = function (event) {
            flexTable();
        };






        // document ready
    });


                // Search




</script>

<div class="tab-content">
    <div class="tab-pane active">
        <div class="table-data">
            <div class="order">
                <div class="head">
                    <h3>Danh Sách Nhân Viên </h3>
                    <i class='bx bx-search'></i>
                    <i class='bx bx-filter'></i>
                    <div>
                        <a asp-controller="HomeAdmin" asp-action="AddStaff" class="create">
                            <button type="button" class="snip1582" asp-controller="HomeAdmin" asp-action="AddStaff">
                                <i></i>Create New
                            </button>
                        </a>
                    </div>
                </div>
                <table>
                    <thead>
                        <tr>

                            <th style="width:20%">
                                Tên nhân viên 
                            </th>
                            <th>
                                Chức vụ 
                            </th>
                            <th>
                                Số điện thoại
                            </th>
                            <th>
                                Email
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>

                                <td>
                                    @Html.DisplayFor(modelItem => item.TenNv)
                                </td>


                                <td>
                                    @Html.DisplayFor(modelItem => item.ChucVu)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Sdtnv)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.EmailNv)
                                </td>
                              
                                <td>
                                    <a class="btn-sm btn-gradient-dark " asp-action="editStaff" asp-route-manv="@item.MaNv">Edit</a>
                                    <a class="btn-sm btn-gradient-danger" asp-action="deleteStaff" asp-route-maStaff="@item.MaNv">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

TTCM_RestaurentManager/Areas/Admin/Views/HomeAdmin/ThongKe.cshtml
@{
    ViewData["Title"] = "ThongKe";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using TTCM_RestaurentManager.Models;
@model List<ThongKe>

<div class="tab-content">
	<div class="tab-pane active">
		<div class="table-data">
			<div class="order">
				<div class="head">
					<h3>Số món ăn được bán</h3>
					<div class="status pending">
						<form class="form" method="POST" asp-controller="HomeAdmin" asp-action="thongke">
							<h6>Check-In</h6>
							<input class="input--style-1" type="text" name="ngayTao" placeholder="mm/dd/yyyy" id="input-start">
							<button class="btn-sm btn-gradient-danger" type="submit">search</button>
						</form>
					</div>

				</div>
				<section class="">
					<div class="">
						<div class="row">
							<section class="">
								<div class="container">
									<div class="row">

										@foreach (var item in Model)
										{
											<div class="col-lg-4 col-sm-6 mb-5">
												<div class="package-info" style="height:300px">
													<h6 class="mt-1"><span class="fa fa-map-marker mr-2"></span>Tên món ăn: @item.dishName</h6>
													<h6 class="mt-1"><span class="fa fa-map-marker mr-2"></span>Số lượng món ăn đã bán: @item.soLuong</h6>
													<img style="width:100px; height:100px" src="@Url.Content("~/Assets/images/"+item.dishImg+".png")" alt="">
												</div>
											</div>
										}
									</div>
								</div>
							</section>
						</div>
					</div>
				</section>
			</div>

		</div>
	</div>
</div>