TTCM_RestaurentManager/Controllers/HomeCustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Elfie.Serialization;
using Microsoft.EntityFrameworkCore;
using TTCM_RestaurentManager.Models;

namespace TTCM_RestaurentManager.Controllers
{
    [Route("customer")]
    public class HomeCustomerController : Controller
    {
        RestaurentManagerContext resDb = new RestaurentManagerContext();
        private readonly ILogger<HomeCustomerController> _logger;

        public HomeCustomerController(ILogger<HomeCustomerController> logger)
        {
            _logger = logger;
        }
        [Route("index")]
        [Route("")]
        public IActionResult Index(int MaLoaiMa)
        {
            var model = from ma in resDb.MonAns
                        where (MaLoaiMa == 0 || ma.MaLoaiMa == MaLoaiMa)
                        select ma;
            if (MaLoaiMa == 0)
            {
                model = resDb.MonAns;
            }
            var kh = getCurrentUser();
            ViewBag.tenKhach = kh.TenKh;
            ViewBag.MaLoaiMa = new SelectList(resDb.LoaiMonAns, "MaLoaiMa", "TenLoaiMa");
            return View(model.ToList());
        }

        [Route("dishDetail")]
		public IActionResult DishDetail(int madish)
		{
			var dishDetail = resDb.MonAns
				.Where(t => t.MaMa == madish)
				.FirstOrDefault();

			ViewBag.DishDetail = dishDetail;
			return View();
		}


		[Route("booking")]
        [HttpGet]
        public IActionResult Booking(int dishId)
        {
            var dishDetail = (from t in resDb.MonAns
                              where t.MaMa == dishId
                              select new
                              {
                                  t.MaMa,
                                  t.TenMa,
                                  t.Gia,
                                  t.ChiTietMa,
                                  t.AnhMa,
                                  t.SoLuongMa
                              }).ToList();
            ViewBag.dishDetail = dishDetail;
            ViewBag.khachHang = getCurrentUser();
            return View();
        }
        [Route("booking")]
        [HttpPost]
        public IActionResult Booking(int soLuong, int dishId)
        {
            if (soLuong <= 0)
            {
                return BadRequest();
            }
            var dish = resDb.MonAns.SingleOrDefault(t => t.MaMa == dishId);
            if (dish == null)
            {
                return BadRequest();
            }
            var kh = getCurrentUser();
            var hd = new HoaDon
            {
                MaKh = kh.MaKh,
                MaMa = dish.MaMa,
                SoLuong = soLuong,
                TongTien = dish.Gia * soLuong
            };
            resDb.HoaDons.Add(hd);
            resDb.SaveChanges();
            dish.SoLuongMa -= soLuong;
            resDb.SaveChanges();
            ViewBag.tenKhach = kh.TenKh;
            ViewBag.sdt = kh.Sdtkh;
            ViewBag.tenDish = dish.TenMa;
            ViewBag.soLuong = soLuong;
            ViewBag.tongTien = hd.TongTien;
            ViewBag.ngayDat = hd.NgayTao;
            return View("BookSuccessFully");
        }
        [Route("history")]
        public IActionResult History(int MaKH = 0)
        {
            var kh = getCurrentUser();
            ViewBag.tenKhach = kh.TenKh;
            if (MaKH == 0)
            {
                MaKH = getMaKH();
            }
            var history = (from hd in resDb.HoaDons
                           join ts in resDb.MonAns on hd.MaMa equals ts.MaMa
                           join Kh in resDb.KhachHangs on hd.MaKh equals Kh.MaKh
                           where String.Equals(Kh.MaKh, MaKH)
                           select new { MonAn = ts, HoaDon = hd, KhachHang = Kh }).OrderByDescending(x => x.HoaDon.NgayTao).ToList();
            ViewBag.History = history;
            return View();
        }





        [Route("myAccount")]
        public IActionResult MyAccount()
        {
            var kh = getCurrentUser();
            var userName = HttpContext.Session.GetString("UserName");
            var tk = (from t in resDb.TaiKhoans where userName.Equals(t.Username) select t).ToList();
            if (tk == null)
            {
                RedirectToAction("Access", "Login");
            }
            ViewBag.tenKhach = kh.TenKh;
            ViewBag.diaChi = kh.DiaChi;
            ViewBag.sdt = kh.Sdtkh;
            ViewBag.userName = tk[0].Username;
            ViewBag.email = tk[0].Email;
            return View();
        }

        private int getMaKH()
        {
            int MaKHang = 0;
            var userName = HttpContext.Session.GetString("UserName");
            var khachhang = (from kh in resDb.KhachHangs
                             join tk in resDb.TaiKhoans on kh.MaKh equals tk.MaKh
                             where String.Equals(tk.Username, userName)
                             select kh).ToList();
            if (khachhang.Count > 0)
            {
                MaKHang = khachhang[0].MaKh;
            }
            return MaKHang;
        }
        private KhachHang getCurrentUser()
        {
            var userName = HttpContext.Session.GetString("UserName");
            var khachhang = (from kh in resDb.KhachHangs
                             join tk in resDb.TaiKhoans on kh.MaKh equals tk.MaKh
                             where String.Equals(tk.Username, userName)
                             select kh).ToList();
            return khachhang[0];
        }
        [Route("menu")]
        public IActionResult Menus(int maLoaiMa)
        {
            // Lấy danh sách món ăn từ database
            List<MonAn> monAnList = resDb.MonAns.ToList();

            // Nếu MaLoaiMa không có giá trị, lấy tất cả các món ăn
            if (maLoaiMa == 0)
            {
                ViewBag.MonAnList = resDb.MonAns.ToList();
            }

            // Lọc danh sách món ăn theo mã loại món ăn nếu có
            if (maLoaiMa != 0)
            {
                monAnList = monAnList.Where(m => m.MaLoaiMa == maLoaiMa).ToList();
            }

            // Đưa danh sách món ăn và SelectList của các loại món ăn vào ViewBag để truyền sang View
            ViewBag.MonAnList = monAnList;
            ViewBag.MaLoaiMa = new SelectList(resDb.LoaiMonAns.ToList(), "MaLoaiMa", "TenLoaiMa", "");

            return View(monAnList);
        }


        [Route("bookOK")]
        [HttpGet]
        public IActionResult BookOK()
        {
            return View();
        }


        [Route("booktable")]
        [HttpGet]
        public IActionResult BookTables()
        {
            return View();
        }
        [ValidateAntiForgeryToken]
        [Route("booktable")]
        [HttpPost]
        public IActionResult BookTables(DatBan ban)
        {
            if (ModelState.IsValid)
            {
                resDb.DatBans.Add(ban);
                resDb.SaveChanges();
                return RedirectToAction("bookOK");
            }
            return View(ban);
        }
        [Route("about")]
        [HttpGet]
        public IActionResult About()
        {
            return View();
        }

    }
}

TTCM_RestaurentManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TTCM_RestaurentManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TTCM_RestaurentManager.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TTCM_RestaurentManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TTCM_RestaurentManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TTCM_RestaurentManager/Views/Shared/_LayoutAboutCustomer.cshtml
<!DOCTYPE html>
<html>

<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="shortcut icon" href="../Assets/images/favicon.png" type="">

    <title> Feane </title>

    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="../Assets/css/bootstrap.css" />

    <!--owl slider stylesheet -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
    <!-- nice select  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/../Assets/css/nice-select.min.css" integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==" crossorigin="anonymous" />
    <!-- font awesome style -->
    <link href="../Assets/css/font-awesome.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="../Assets/css/style.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="../Assets/css/responsive.css" rel="stylesheet" />

</head>

<body class="sub_page">

    <div class="hero_area">
        <div class="bg-box">
            <img src="../Assets/images/hero-bg.jpg" alt="">
        </div>
        <!-- header section strats -->
        @await Html.PartialAsync("_PartialHeaderCustomer")
       @* <header class="header_section">
            <div class="container">
                <nav class="navbar navbar-expand-lg custom_nav-container ">
                    <a class="navbar-brand" href="index.html">
                        <span>
                            Feane
                        </span>
                    </a>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class=""> </span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav  mx-auto ">
                            <li class="nav-item ">
                                <a class="nav-link" href="index.html">Home </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="menu.html">Menu</a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="about.html">About <span class="sr-only">(current)</span> </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="book.html">Book Table</a>
                            </li>
                        </ul>
                        <div class="user_option">
                            <a href="" class="user_link">
                                <i class="fa fa-user" aria-hidden="true"></i>
                            </a>
                            <a class="cart_link" href="#">
                                <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 456.029 456.029" style="enable-background:new 0 0 456.029 456.029;" xml:space="preserve">
                                <g>
                                <g>
                                <path d="M345.6,338.862c-29.184,0-53.248,23.552-53.248,53.248c0,29.184,23.552,53.248,53.248,53.248
                   c29.184,0,53.248-23.552,53.248-53.248C398.336,362.926,374.784,338.862,345.6,338.862z" />
                    </g>
                  </g>
                                <g>
                                <g>
                                <path d="M439.296,84.91c-1.024,0-2.56-0.512-4.096-0.512H112.64l-5.12-34.304C104.448,27.566,84.992,10.67,61.952,10.67H20.48
                   C9.216,10.67,0,19.886,0,31.15c0,11.264,9.216,20.48,20.48,20.48h41.472c2.56,0,4.608,2.048,5.12,4.608l31.744,216.064
                   c4.096,27.136,27.648,47.616,55.296,47.616h212.992c26.624,0,49.664-18.944,55.296-45.056l33.28-166.4
                   C457.728,97.71,450.56,86.958,439.296,84.91z" />
                    </g>
                  </g>
                                <g>
                                <g>
                                <path d="M215.04,389.55c-1.024-28.16-24.576-50.688-52.736-50.688c-29.696,1.536-52.224,26.112-51.2,55.296
                   c1.024,28.16,24.064,50.688,52.224,50.688h1.024C193.536,443.31,216.576,418.734,215.04,389.55z" />
                    </g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                </svg>
                            </a>
                            <form class="form-inline">
                                <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit">
                                    <i class="fa fa-search" aria-hidden="true"></i>
                                </button>
                            </form>
                            <a href="" class="order_online">
                                Order Online
                            </a>
                        </div>
                    </div>
                </nav>
            </div>
        </header>*@
        <!-- end header section -->
    </div>

    <!-- about section -->
    @RenderBody()
 @*   <section class="about_section layout_padding">
        <div class="container  ">

            <div class="row">
                <div class="col-md-6 ">
                    <div class="img-box">
                        <img src="../Assets/images/about-img.png" alt="">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="detail-box">
                        <div class="heading_container">
                            <h2>
                                We Are Feane
                            </h2>
                        </div>
                        <p>
                            There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration
                            in some form, by injected humour, or randomised words which don't look even slightly believable. If you
                            are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in
                            the middle of text. All
                        </p>
                        <a href="">
                            Read More
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
*@
    <!-- end about section -->
    <!-- footer section -->
    @await Html.PartialAsync("_PartialFooter")
   @* <footer class="footer_section">
        <div class="container">
            <div class="row">
                <div class="col-md-4 footer-col">
                    <div class="footer_contact">
                        <h4>
                            Contact Us
                        </h4>
                        <div class="contact_link_box">
                            <a href="">
                                <i class="fa fa-map-marker" aria-hidden="true"></i>
                                <span>
                                    Location
                                </span>
                            </a>
                            <a href="">
                                <i class="fa fa-phone" aria-hidden="true"></i>
                                <span>
                                    Call +01 1234567890
                                </span>
                            </a>
                            <a href="">
                                <i class="fa fa-envelope" aria-hidden="true"></i>
                                <span>
                                    demo@gmail.com
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 footer-col">
                    <div class="footer_detail">
                        <a href="" class="footer-logo">
                            Feane
                        </a>
                        <p>
                            Necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with
                        </p>
                        <div class="footer_social">
                            <a href="">
                                <i class="fa fa-facebook" aria-hidden="true"></i>
                            </a>
                            <a href="">
                                <i class="fa fa-twitter" aria-hidden="true"></i>
                            </a>
                            <a href="">
                                <i class="fa fa-linkedin" aria-hidden="true"></i>
                            </a>
                            <a href="">
                                <i class="fa fa-instagram" aria-hidden="true"></i>
                            </a>
                            <a href="">
                                <i class="fa fa-pinterest" aria-hidden="true"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 footer-col">
                    <h4>
                        Opening Hours
                    </h4>
                    <p>
                        Everyday
                    </p>
                    <p>
                        10.00 Am -10.00 Pm
                    </p>
                </div>
            </div>
            <div class="footer-info">
                <p>
                    &copy; <span id="displayYear"></span> All Rights Reserved By
                    <a href="https://html.design/">Free Html Templates</a><br><br>
                    &copy; <span id="displayYear"></span> Distributed By
                    <a href="https://themewagon.com/" target="_blank">ThemeWagon</a>
                </p>
            </div>
        </div>
    </footer>*@
    <!-- footer section -->
    <!-- jQery -->
    <script src="../Assets/js/jquery-3.4.1.min.js"></script>
    <!-- popper js -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <!-- bootstrap js -->
    <script src="../Assets/js/bootstrap.js"></script>
    <!-- owl slider -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
    </script>
    <!-- isotope js -->
    <script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></script>
    <!-- nice select -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/../Assets/js/jquery.nice-select.min.js"></script>
    <!-- custom js -->
    <script src="../Assets/js/custom.js"></script>
    <!-- Google Map -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
    </script>
    <!-- End Google Map -->

</body>

</html>

TTCM_RestaurentManager/Views/Shared/_LayoutMyAccount.cshtml
@{
    ViewData["Title"] = "MyAccount";
    Layout = null;
}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500&display=swap" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Source+Serif+Pro:400,600&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="../Template/TemplateMyAccount/fonts/icomoon/style.css">

    <link rel="stylesheet" href="../Template/TemplateMyAccount/css/owl.carousel.min.css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="../Template/TemplateMyAccount/css/bootstrap.min.css">

    <!-- Style -->
    <link rel="stylesheet" href="../Template/TemplateMyAccount/css/style.css">
    <link rel="stylesheet" href="../Template/TemplateMyAccount/css/custom.css">

    <title>My Account</title>
</head>
<body class="show-sidebar" style="width:75%">

    <aside class="sidebar">
        @*<div class="toggle">
        <a href="#" class="burger js-menu-toggle" data-toggle="collapse" data-target="#main-navbar">
        <span></span>
        </a>
        </div>*@
        <div class="side-inner">

            <div class="profile">
                <img src="../Assets/images/te4.jpg" alt="Image">
                <h3 class="name">@ViewBag.tenKhach</h3>
                <span class="country">Web Designer</span>
            </div>


            <div class="nav-menu">
                <ul>
                    <li><a asp-controller="HomeCustomer" asp-action="MyAccount"><span class="icon-account mr-3"></span>Account</a></li>
                    <li> <a asp-controller="customer" asp-action="history"><span class="icon-history mr-3"></span>History</a></li>
                    <li><a asp-controller="HomeCustomer" asp-action="Index"><i class="fas fa-arrow-left"></i> Previous Page</a></li>
                    <li>
                        <a asp-controller="Access" asp-action="Logout">
                            <span class="icon-sign-out mr-3"></span>
                            Sign out
                        </a>
                    </li>
                </ul>
            </div>
        </div>

    </aside>
    <main>
        <div class="site-section">
            <div class="container">
                @*<div class="row justify-content-center">*@
                @*<div class="container-fluid mt--7">*@
                @*<div class="row">*@
                @RenderBody()
                @*</div>*@
                @*</div>*@
                @*</div>*@
            </div>
        </div>
    </main>

    <script src="../../Template/TemplateMyAccount/js/jquery-3.3.1.min.js"></script>
    <script src="../../Template/TemplateMyAccount/js/popper.min.js"></script>
    <script src="../../Template/TemplateMyAccount/js/bootstrap.min.js"></script>
    <script src="../../Template/TemplateMyAccount/js/main.js"></script>
</body>
</html>

TTCM_RestaurentManager/Views/Shared/_PartialFooter.cshtml
<footer class="footer_section">
    <div class="container">
        <div class="row">
            <div class="col-md-4 footer-col">
                <div class="footer_contact">
                    <h4>
                        Contact Us
                    </h4>
                    <div class="contact_link_box">
                        <a href="">
                            <i class="fa fa-map-marker" aria-hidden="true"></i>
                            <span>
                                Location
                            </span>
                        </a>
                        <a href="">
                            <i class="fa fa-phone" aria-hidden="true"></i>
                            <span>
                                Call +01 1234567890
                            </span>
                        </a>
                        <a href="">
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                            <span>
                                quochat00@gmail.com
                            </span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-4 footer-col">
                <div class="footer_detail">
                    <a href="" class="footer-logo">
                        Feane
                    </a>
                    <p>
                        Necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with
                    </p>
                    <div class="footer_social">
                        <a href="">
                            <i class="fa fa-facebook" aria-hidden="true"></i>
                        </a>
                        <a href="">
                            <i class="fa fa-twitter" aria-hidden="true"></i>
                        </a>
                        <a href="">
                            <i class="fa fa-linkedin" aria-hidden="true"></i>
                        </a>
                        <a href="">
                            <i class="fa fa-instagram" aria-hidden="true"></i>
                        </a>
                        <a href="">
                            <i class="fa fa-pinterest" aria-hidden="true"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-4 footer-col">
                <h4>
                    Opening Hours
                </h4>
                <p>
                    Everyday
                </p>
                <p>
                    10.00 Am -10.00 Pm
                </p>
            </div>
        </div>
        <div class="footer-info">
            <p>
                &copy; <span id="displayYear"></span> All Rights Reserved By
                <a href="https://html.design/">Free Html Templates</a><br><br>
                &copy; <span id="displayYear"></span> Distributed By
                <a href="https://themewagon.com/" target="_blank">ThemeWagon</a>
            </p>
        </div>
    </div>
</footer>